name: travelmatex
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  connectivity_plus: ^4.0.2
  firebase_auth: ^4.10.0
  firebase_storage: ^11.2.7
  get: ^4.6.5
  google_fonts: ^6.1.0
  rive: ^0.11.17
  flashy_tab_bar2: ^0.0.6
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.14
  shimmer: ^3.0.0
  intl: ^0.19.0
  table_calendar: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/images/popular/
